### ISSUE TITLE
Make item.js enums available to high level code

### ISSUE THREAD

**Issue by louis030195** [MephisTools/diablo2-protocol#56]
https://github.com/MephisTools/diablo2-protocol/blob/master/lib/utils/item.js

it would be useful to be able to use these enum to avoid hardcoding numbers in high level code

**Comment by rom1504** [comment]
It should be moved to diablo2-data

**Comment by louis030195** [comment]
done

https://github.com/MephisTools/node-diablo2-data/commit/853ce601ba883ee4e1b721d6cd7928e9434f6416
